# Generated by Django 2.2.6 on 2019-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
