version: "3"

services:

    db:
        image:  mysql:5.7 # mysql镜像，最好先拉取到本地
        environment:
          MYSQL_DATABASE: shop
          MYSQL_ROOT_PASSWORD: 760942500
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
        ]
        networks:
          web-network:
            aliases:
              - db
        volumes:
            - /srv/db:/var/lib/mysql  # 将宿主机与容器中的文件映射
        restart: always  # 若容器运行出现问题，会自动重启容器

    web:
        build: ./myshop
        volumes:
            - ./myshop:/app/myshop
        command: bash start.sh  # 执行命令，有多种格式
        ports:
            - "8081:8081"
        networks:
          web-network:
            aliases:
              - web
        depends_on:
            - db
            - redis
        restart: always

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./myshop/static_new:/usr/share/nginx/html/static
        networks:
          web-network:
            aliases:
              - nginx
        depends_on:
            - web
        restart: always

    tracker:
        build: ./tracker
        networks:
          web-network:
            aliases:
              - tracker
        depends_on:
            - web
        volumes:
            - ./tracker/fdfs_tracker:/var/fdfs
        restart: always

    storage:
        build: ./storage
        networks:
          web-network:
            aliases:
              - storage
        depends_on:
            - tracker
        volumes:
            - ./storage/fdfs_storage:/var/fdfs
        environment:
            TRACKER_SERVER: tracker:22122             #设置为公网ip
        restart: always

    redis:
        image: redis
        networks:
          web-network:
            aliases:
              - redisdb
        restart: always

networks:
  web-network: